version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    ports:
      - "8000:8000"      # 把 Jenkins 的 HTTP 改为 8000
      - "50000:50000"    # JNLP Agent port
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    volumes:
      - jenkins_home:/var/jenkins_home
    command: >
      bash -c "java -jar /usr/share/jenkins/jenkins.war --httpPort=8000"

volumes:
  jenkins_home:
